export const ERROR_CODES = {
    TOKEN_EXPIRED: -3,
    USER_BLOCKING: -12,
    USER_DELETED: -18,
    USER_BAN: -21,
    CALL_INACTIVE: -310,
    LIMITED_ACCESS: -315,
    FOLLOWER_ONLY: -317,
    USER_BANNED_CALL: -321,
    MUTUAL_ONLY: -402,
    REQUEST_LIMIT: -5301,
  };  